import { IErrorMessage } from '../err-message-interface';

export const arErrorMessage: IErrorMessage = {
  YOU_CANT_ADD_REPLY_OR_RETWEET_TO_ADS_AND_NEWS:
    "You can't add reply or retweet to ads and news",
  YOU_DIDNT_LIKE_THIS_TWEET: "You didn't like this tweet",
  YOU_CANT_LIKE_AD: 'ممنوع اضافة اعجاب للإعلانات',
  TWEET_NOT_FOUND: 'لم يتم العثور على التغريدة',
  ALREADY_FOLLOW_THIS_USER: 'انت متابع لهذا المستخدم',
  YOU_CANT_ADD_YOURSELF: 'لا يمكن متابعة نفسك',
  PERMISSION_DENIED: 'لا يوجد اذن',
  UNAUTHORIZED: 'لم يتم تسجيل الدخول',
  EMAIL_ALREADY_EXISTS: 'الايميل مستخدم من قبل',
  PHONE_ALREADY_EXISTS: 'الهاتف مستخدم من قبل',
  INVALID_CREDENTIALS: 'بيانات الاعتماد غير صالحة',
  BLOCKED_USER: 'مستخدم محظور',
  USER_PHONE_NOT_VERIFIED_YET: 'لم يتم التحقق من هاتف المستخدم بعد',
  USER_DOES_NOT_EXIST: 'المستخدم غير موجود',
  USER_EMAIL_IS_NOT_VERIFIED_YET: 'لم يتم التحقق من البريد الإلكتروني للمستخدم بعد',
  VERIFICATION_CODE_NOT_EXIST: 'رمز التحقق غير موجود',
  EXPIRED_VERIFICATION_CODE: 'رمز التحقق منتهي الصلاحية',
  WRONG_PASSWORD: 'كلمة مرور خاطئة',
  CONFIGURATION_SHOULD_HAS_UNIQUE_KEY: 'يجب أن يحتوي التكوين على مفتاح فريد',
  CONFIGURATION_NOT_EXISTS: 'هذا التكوين غير موجود',
  NOTIFICATION_DOES_NOT_EXIST: 'لم يتم العثور على إشعار',
  USER_PHONE_ALREADY_VERIFIED: 'تم بالفعل التحقق من هاتف المستخدم',
  INCORRECT_DATE: 'تاريخ غير صحيح',
  FROM_VALUE_HIGHER_THAN_OR_EQUAL_TO_VALUE:
    'From value cannot be higher than or equal TO value',
  PROVIDE_AVAILABILITY_FOR_ALL_DAYS: 'Provide availability for all days',
  SECURITY_GROUP_NAME_ALREADY_EXISTS:
    'Security group with a same name already exists',
  SECURITY_GROUP_DOES_NOT_EXIST: 'Security group does not exist',
  INCORRECT_PHONE_OR_PASSWORD: 'Incorrect phone number or password',
  CONFIRM_PASSWORD_DOESN_T_MATCH: 'Confirm password does not match',
  INVALID_EMAIL: 'Invalid email',
  SHIFTS_DURATION_LESS_THAN_APPOINTMENT_DURATION:
    'Availability shifts duration could not be less than appointment duration',
  BANK_INFORMATION_DOES_NOT_EXIST: 'Bank information does not exist ',
  CONTACT_MESSAGE_NOT_EXIST: 'Contact message not exist',
  FAQ_DOES_NOT_EXIST: 'Faq does not exist',
  CANT_DELETE_SUPER_ADMIN_GROUP: 'Super admin group should not be deleted',
  INVALID_APPOINTMENT_MESSAGE_TYPE: 'Invalid appointment message type',
  INVALID_PHONE_NUMBER: 'رقم الهاتف غير صحيح',
  CATEGORY_DOES_NOT_EXIST: 'لا يوجد كاتيجوري يا نجم',
  CATEGORY_ENUM_NOT_VALID: ' اسم غير معرف',
  CATEGORY_ALREADY_EXISTS: 'موجود بالفعل ',
};
